### ISSUE TITLE
Possible Missing Data Field

### ISSUE THREAD

**Issue by dbltoe** [proseLA/square_webPay#16]
Sanitized log file
`[10-Apr-2022 19:17:55 US/Central] Request URI: /index.php?main_page=checkout_process, IP address: ***.***.***.***
#1 trigger_error() called at [/includes/classes/db/mysql/query_factory.php:171]
#2 queryFactory->show_error() called at [/includes/classes/db/mysql/query_factory.php:143]
#3 queryFactory->set_error() called at [/includes/classes/db/mysql/query_factory.php:270]
#4 queryFactory->Execute() called at [/includes/functions/database.php:44]
#5 zen_db_perform() called at [/includes/classes/order.php:723]
#6 order->create() called at [/includes/modules/checkout_process.php:94]
#7 require(/includes/modules/checkout_process.php) called at [/includes/modules/pages/checkout_process/header_php.php:14]
#8 require(/includes/modules/pages/checkout_process/header_php.php) called at [/index.php:35]
--> PHP Fatal error: 1054:Unknown column 'language_code' in 'field list' :: INSERT INTO orders (customers_id, customers_name, customers_company, customers_street_address, customers_suburb, customers_city, customers_postcode, customers_state, customers_country, customers_telephone, customers_email_address, customers_address_format_id, delivery_name, delivery_company, delivery_street_address, delivery_suburb, delivery_city, delivery_postcode, delivery_state, delivery_country, delivery_address_format_id, billing_name, billing_company, billing_street_address, billing_suburb, billing_city, billing_postcode, billing_state, billing_country, billing_address_format_id, payment_method, payment_module_code, shipping_method, shipping_module_code, coupon_code, cc_type, cc_owner, cc_number, cc_expires, date_purchased, orders_status, order_total, order_tax, currency, currency_value, ip_address, language_code, order_weight) VALUES ('609', 'Mary Smith', '', '***********', '', 'Atlanta', '30815', 'Georgia', 'United States', '*******', 'annie0akley27@gmail.com', '2', 'Mary Smith', '', '********', '', 'Atlanta', '30815', 'Georgia', 'United States', '2', 'Mary Smith', '', '*******', '', 'Atlanta', '30815', 'Georgia', 'United States', '2', 'Credit Card', 'square_webPay', 'Flat Rate (Best Way)', 'flat', '', 'VISA', '', 'xxxxxx****', '0223', now(), '2', '73.72', '0', 'USD', '1.000000', '73.20.220.21 - 73.20.220.21', 'en', '0') ==> (as called by) /includes/functions/database.php on line 44 <== in /includes/classes/db/mysql/query_factory.php on line 171.`

I have not checked other than 1.5.7d installation SQL files but, the language_id field WAS missing from the database of this site.  It was an upgrade from 1.5.6c straight to 1.5.7d.  There was also no language_id field in the 1.5.6c database used in the upgrade.

**  Further investigation shows that the language_id field is not set in an initial install of 1.5.6c

So......

I'm rethinking my statement that WebPay is working with .5.6c without adding the field to the database's orders table.

**Comment by dbltoe** [comment]
Also, on some sites, getting MODULE_PAYMENT_SQUARE_TOKEN_EXPIRES_AT and MODULE_PAYMENT_SQUARE_APPLICATION_ID missing a define.  It should be in the configuration table of the database and is in 1.5.7# but not in the 1.5.6c DBs that I can get a look at.

Wondering if these should be set to null originally and updated when Authorizing with Square or if Square should be establishing them in the DB during Authorization.

**Comment by proseLA** [comment]
john,
as i previously mentioned, please open a new issue for every issue that you have.  do not post multiple threads in 1 issue.  it makes it easier to keep track of them.

neither one of the issues you have presented here are related to this module.

best.
