### ISSUE TITLE
quotes cause problems

### ISSUE THREAD

**Issue by proseLA** [proseLA/square_webPay#20]
in names and address fields.

**Comment by dbltoe** [comment]
Don't know about outside the US but, only five US place names are permitted to use an apostrophe: Martha's Vineyard in the state of Massachusetts, Ike's Point in New Jersey, John E's Pond in Rhode Island, Carlos Elmer's Joshua View in Arizona, and Clark's Mountain in Oregon (the last of the five to be approved, in 2002).

The same governing board dislikes apostrophes in any place or name.

Seems like surnames are the only time the percentages of running into an apostrophe is likely,

Still, to be correct......
